[package]
name = "spearman"
version = "0.1.0"
edition = "2024"

[dependencies]
windows = { version = "0.62.2", features = [
    "Win32_Foundation",
    "Win32_System_Console",
    "Win32_System_LibraryLoader",
    "Win32_System_SystemServices",
    "Win32_UI_WindowsAndMessaging",
] }
winapi = { version = "0.3.9", features = ["ntdef", "minwindef", "consoleapi", "processthreadsapi", "psapi", "handleapi", "tlhelp32", "memoryapi"] }
# ilhook = "2.3.0"
colored = "3.1.1"

[lib]
crate-type = ["cdylib"] # compile to dll
# name = "version" # call the dll "version.dll" instead of "spearman.dll"

# ditched for dynamic forwarding
# [target.x86_64-pc-windows-msvc]
# rustflags = ["-Clink-arg=/DEF:imposter.def"] # automatically link to version_orig.dll exports when building
# why version.dll? the 17 exports are stable and havent changed since 2007.